<?php

namespace App\Modules\Transcripta\Services;

use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class TranscriptaService
{
    public function process(UploadedFile $file): string
    {
        set_time_limit(3600); // Increase max execution time to 1 hour

        $openaiKey = config('services.openai.api_key');
        $geminiKey = config('services.gemini.api_key');

        // Priority 1: OpenAI
        if (!empty($openaiKey)) {
            try {
                $response = Http::withOptions([
                    'verify' => false,
                ])->withHeaders([
                    'Authorization' => 'Bearer ' . $openaiKey,
                ])->timeout(120)->attach(
                    'file', file_get_contents($file->getRealPath()), $file->getClientOriginalName()
                )->attach(
                    'model', 'whisper-1'
                )->post('https://api.openai.com/v1/audio/transcriptions');

                if ($response->successful()) {
                    return $response->json('text') ?? 'No text found in audio.';
                }

                $error = $response->json('error.message') ?? $response->body();
                
                // If not a quota error, log it and maybe return it? 
                // But we want to try Gemini if OpenAI fails for ANY reason if we have a key.
                Log::warning('OpenAI Transcription Error: ' . $error);

            } catch (\Exception $e) {
                Log::error('Transcripta OpenAI Exception: ' . $e->getMessage());
            }
        }

        // Priority 2: Gemini (Free Tier)
        if (!empty($geminiKey)) {
            return $this->processWithGemini($file, $geminiKey);
        }

        // Fallback Message
        return "Notice: AI Processing Failed.\n\n1. OpenAI: " . (empty($openaiKey) ? "Key missing" : "Quota exceeded or error") . ".\n2. Gemini: Key missing.\n\n[Simulated Transcription]\nThis is a simulated transcription of the audio file '{$file->getClientOriginalName()}'. Please provide a valid OPENAI_API_KEY or GEMINI_API_KEY in your .env file to enable real transcription.";
    }

    private function processWithGemini(UploadedFile $file, string $apiKey): string
    {
        try {
            $mimeType = $file->getMimeType();
            // Normalize mime types
            if ($mimeType === 'audio/mpeg') $mimeType = 'audio/mp3';
            
            // For larger files (e.g. > 10MB) or video files, use the File API
            $isLargeFile = $file->getSize() > 10 * 1024 * 1024;
            $isVideo = str_starts_with($mimeType, 'video/');

            if ($isLargeFile || $isVideo) {
                return $this->processWithGeminiFileApi($file, $apiKey, $mimeType);
            }

            // Inline processing for small audio files
            $base64Data = base64_encode(file_get_contents($file->getRealPath()));
            
            $response = Http::withOptions(['verify' => false])
                ->withHeaders(['Content-Type' => 'application/json'])
                ->timeout(300)
                ->post("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={$apiKey}", [
                    'contents' => [
                        [
                            'parts' => [
                                ['text' => "Transcribe this media file verbatim. Speaker labels are helpful."],
                                [
                                    'inline_data' => [
                                        'mime_type' => $mimeType,
                                        'data' => $base64Data
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]);

            if ($response->successful()) {
                return $response->json('candidates.0.content.parts.0.text') ?? 'No transcription generated by Gemini.';
            }

            $error = $response->body();
            Log::error('Gemini Transcription Error: ' . $error);
            return "Error from Gemini Service: " . $error;

        } catch (\Exception $e) {
            Log::error('Transcripta Gemini Exception: ' . $e->getMessage());
            return "System Error (Gemini): " . $e->getMessage();
        }
    }

    private function processWithGeminiFileApi(UploadedFile $file, string $apiKey, string $mimeType): string
    {
        $fileSize = $file->getSize();
        $filePath = $file->getRealPath();

        // 1. Initiate Resumable Upload
        $initResponse = Http::withOptions(['verify' => false])
            ->withHeaders([
                'X-Goog-Upload-Protocol' => 'resumable',
                'X-Goog-Upload-Command' => 'start',
                'X-Goog-Upload-Header-Content-Length' => $fileSize,
                'X-Goog-Upload-Header-Content-Type' => $mimeType,
                'Content-Type' => 'application/json',
            ])
            ->post("https://generativelanguage.googleapis.com/upload/v1beta/files?key={$apiKey}", [
                'file' => ['display_name' => $file->getClientOriginalName()]
            ]);

        if (!$initResponse->successful()) {
            throw new \Exception("Failed to initiate upload: " . $initResponse->body());
        }

        $uploadUrl = $initResponse->header('X-Goog-Upload-URL');

        // 2. Upload File Content
        $fileHandle = fopen($filePath, 'r');
        $fileData = fread($fileHandle, $fileSize);
        fclose($fileHandle);

        $uploadResponse = Http::withOptions(['verify' => false])
            ->timeout(3600) // 1 hour timeout for upload
            ->withHeaders([
                'Content-Length' => $fileSize,
                'X-Goog-Upload-Offset' => 0,
                'X-Goog-Upload-Command' => 'upload, finalize',
            ])
            ->withBody($fileData, $mimeType)
            ->post($uploadUrl);

        if (!$uploadResponse->successful()) {
            throw new \Exception("Failed to upload file content: " . $uploadResponse->body());
        }

        $fileUri = $uploadResponse->json('file.uri');
        $fileState = $uploadResponse->json('file.state');
        $fileName = $uploadResponse->json('file.name'); // resource name

        // 3. Wait for processing if needed
        $attempts = 0;
        while ($fileState === 'PROCESSING' && $attempts < 150) { // Wait up to ~5 minutes
            sleep(2);
            $checkResponse = Http::withOptions(['verify' => false])
                ->get("https://generativelanguage.googleapis.com/v1beta/{$fileName}?key={$apiKey}");
            
            if ($checkResponse->successful()) {
                $fileState = $checkResponse->json('state');
            }
            $attempts++;
        }

        if ($fileState !== 'ACTIVE') {
            throw new \Exception("File failed to process. State: {$fileState}");
        }

        // 4. Generate Content
        $response = Http::withOptions(['verify' => false])
            ->withHeaders(['Content-Type' => 'application/json'])
            ->timeout(600) // 10 minutes for video processing
            ->post("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={$apiKey}", [
                'contents' => [
                    [
                        'parts' => [
                            ['text' => "Transcribe this media file verbatim. Speaker labels are helpful."],
                            [
                                'file_data' => [
                                    'mime_type' => $mimeType,
                                    'file_uri' => $fileUri
                                ]
                            ]
                        ]
                    ]
                ]
            ]);

        if ($response->successful()) {
            return $response->json('candidates.0.content.parts.0.text') ?? 'No transcription generated.';
        }

        $error = $response->body();
        Log::error('Gemini File API Error: ' . $error);
        return "Error from Gemini Service (File API): " . $error;
    }
}
